# Generated by Django 6.0.2 on 2026-02-16 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_job_skills'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='employment_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='job',
            name='min_experience_years',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('current_location', models.CharField(blank=True, max_length=120)),
                ('years_experience', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notice_period_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('expected_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('consent_given', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='core.job')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_type', models.CharField(choices=[('portfolio', 'Portfolio'), ('github', 'GitHub'), ('case_study', 'Case Study'), ('loom', 'Loom'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='artifacts/')),
                ('notes', models.TextField(blank=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='core.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('recommendation', models.CharField(choices=[('yes', 'Yes'), ('hold', 'Hold'), ('no', 'No')], default='hold', max_length=10)),
                ('strengths', models.JSONField(blank=True, default=list)),
                ('gaps', models.JSONField(blank=True, default=list)),
                ('missing_evidence', models.JSONField(blank=True, default=list)),
                ('evaluated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='core.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='BucketScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(choices=[('skills_evidence', 'Skills Evidence'), ('problem_solving', 'Problem Solving'), ('role_fit', 'Role Fit'), ('work_style', 'Work Style')], max_length=25)),
                ('raw_score', models.DecimalField(decimal_places=1, max_digits=3)),
                ('weighted_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rationale', models.TextField(blank=True)),
                ('candidate_evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bucket_scores', to='core.candidateevaluation')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('parsed_json', models.JSONField(blank=True, null=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resume', to='core.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='JobEvaluationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_skills_evidence', models.PositiveSmallIntegerField(default=25)),
                ('weight_problem_solving', models.PositiveSmallIntegerField(default=30)),
                ('weight_role_fit', models.PositiveSmallIntegerField(default=30)),
                ('weight_work_style', models.PositiveSmallIntegerField(default=15)),
                ('shortlist_threshold', models.DecimalField(decimal_places=2, default=70.0, max_digits=5)),
                ('review_threshold', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_config', to='core.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('requirement_type', models.CharField(choices=[('must', 'Must'), ('nice', 'Nice')], default='must', max_length=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='core.job')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('question_type', models.CharField(choices=[('knockout_bool', 'Knockout Bool'), ('single_choice', 'Single Choice'), ('multi_choice', 'Multi Choice'), ('short_text', 'Short Text'), ('long_text', 'Long Text'), ('number', 'Number'), ('file', 'File Upload'), ('url', 'URL')], max_length=20)),
                ('is_required', models.BooleanField(default=True)),
                ('is_knockout', models.BooleanField(default=False)),
                ('knockout_rule', models.JSONField(blank=True, null=True)),
                ('bucket', models.CharField(blank=True, choices=[('skills_evidence', 'Skills Evidence'), ('problem_solving', 'Problem Solving'), ('role_fit', 'Role Fit'), ('work_style', 'Work Style')], max_length=25)),
                ('order', models.PositiveIntegerField(default=0)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.job')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='KnockoutResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField(default=True)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knockout_results', to='core.candidate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.screeningquestion')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('answer_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.candidate')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='core.screeningquestion')),
            ],
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['job', 'email'], name='core_candid_job_id_29d14a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bucketscore',
            unique_together={('candidate_evaluation', 'bucket')},
        ),
        migrations.AlterUniqueTogether(
            name='candidateanswer',
            unique_together={('candidate', 'question')},
        ),
    ]
