SKILL_LIST = [
    "HTML",
    "CSS",
    "JavaScript",
    "TypeScript",
    "Web Accessibility",
    "Responsive Design",
    "Sass",
    "Less",
    "Tailwind CSS",
    "Bootstrap",
    "Material UI",
    "Chakra UI",
    "Styled Components",
    "CSS Modules",
    "Webpack",
    "Vite",
    "Babel",
    "ESLint",
    "Prettier",
    "Jest",
    "Vitest",
    "Cypress",
    "Playwright",
    "Puppeteer",
    "React",
    "Next.js",
    "Redux",
    "Vue.js",
    "Nuxt.js",
    "Angular",
    "Svelte",
    "SvelteKit",
    "SolidJS",
    "Astro",
    "Node.js",
    "Express.js",
    "NestJS",
    "Fastify",
    "Koa",
    "Hapi",
    "Deno",
    "Bun",
    "REST APIs",
    "GraphQL",
    "Apollo",
    "gRPC",
    "WebSockets",
    "OAuth",
    "OpenID Connect",
    "JWT",
    "API Gateway",
    "Rate Limiting",
    "Caching",
    "Redis",
    "Memcached",
    "CDN",
    "Load Balancing",
    "Microservices",
    "Monolith Architecture",
    "Serverless",
    "AWS Lambda",
    "Azure Functions",
    "Google Cloud Functions",
    "Kubernetes",
    "Docker",
    "Docker Compose",
    "Helm",
    "Service Mesh",
    "Istio",
    "Linkerd",
    "Terraform",
    "Pulumi",
    "Ansible",
    "Chef",
    "Puppet",
    "CI/CD",
    "GitHub Actions",
    "GitLab CI",
    "Jenkins",
    "CircleCI",
    "Travis CI",
    "Bash",
    "Linux",
    "Unix",
    "Windows",
    "macOS",
    "Git",
    "SVN",
    "Mercurial",
    "Agile",
    "Scrum",
    "Kanban",
    "DevOps",
    "SRE",
    "Monitoring",
    "Logging",
    "Prometheus",
    "Grafana",
    "ELK Stack",
    "OpenTelemetry",
    "Datadog",
    "New Relic",
    "Splunk",
    "Python",
    "Java",
    "C",
    "C++",
    "C#",
    "Go",
    "Rust",
    "Kotlin",
    "Swift",
    "Objective-C",
    "Scala",
    "Ruby",
    "PHP",
    "Perl",
    "R",
    "MATLAB",
    "Julia",
    "Haskell",
    "Erlang",
    "Elixir",
    "Lua",
    "Dart",
    "Flutter",
    "Android",
    "iOS",
    "React Native",
    "Xamarin",
    "Unity",
    "Unreal Engine",
    "Game Development",
    "Data Structures",
    "Algorithms",
    "Big O Analysis",
    "System Design",
    "Distributed Systems",
    "Concurrency",
    "Multithreading",
    "Parallel Computing",
    "Networking",
    "TCP/IP",
    "HTTP",
    "DNS",
    "TLS",
    "SSL",
    "Network Security",
    "Cryptography",
    "Public Key Infrastructure",
    "Identity and Access Management",
    "Zero Trust",
    "Vulnerability Scanning",
    "Penetration Testing",
    "OWASP",
    "Threat Modeling",
    "Secure Coding",
    "Static Analysis",
    "Dynamic Analysis",
    "Fuzz Testing",
    "SQL",
    "PostgreSQL",
    "MySQL",
    "SQLite",
    "SQL Server",
    "Oracle",
    "MongoDB",
    "Cassandra",
    "DynamoDB",
    "Redis",
    "Neo4j",
    "CouchDB",
    "Firestore",
    "Elasticsearch",
    "Kafka",
    "RabbitMQ",
    "ActiveMQ",
    "NATS",
    "SQS",
    "SNS",
    "Event-Driven Architecture",
    "ETL",
    "ELT",
    "Data Warehousing",
    "Data Lakes",
    "Data Modeling",
    "OLTP",
    "OLAP",
    "dbt",
    "Airflow",
    "Luigi",
    "Prefect",
    "Spark",
    "Hadoop",
    "Hive",
    "Presto",
    "Trino",
    "Flink",
    "Beam",
    "Snowflake",
    "BigQuery",
    "Redshift",
    "Databricks",
    "Tableau",
    "Power BI",
    "Looker",
    "Metabase",
    "Superset",
    "Data Visualization",
    "Data Cleaning",
    "Feature Engineering",
    "Statistics",
    "Probability",
    "A/B Testing",
    "Experiment Design",
    "Time Series",
    "Forecasting",
    "Optimization",
    "Linear Algebra",
    "Calculus",
    "Machine Learning",
    "Deep Learning",
    "AI",
    "NLP",
    "Computer Vision",
    "Reinforcement Learning",
    "Supervised Learning",
    "Unsupervised Learning",
    "Semi-Supervised Learning",
    "Transfer Learning",
    "Federated Learning",
    "Model Evaluation",
    "Model Monitoring",
    "MLOps",
    "Model Serving",
    "Feature Store",
    "TensorFlow",
    "Keras",
    "PyTorch",
    "Scikit-learn",
    "XGBoost",
    "LightGBM",
    "CatBoost",
    "Hugging Face",
    "Transformers",
    "Sentence Transformers",
    "BERT",
    "RoBERTa",
    "GPT",
    "LLMs",
    "Prompt Engineering",
    "RAG",
    "Vector Databases",
    "FAISS",
    "Pinecone",
    "Weaviate",
    "Milvus",
    "Chroma",
    "LangChain",
    "LlamaIndex",
    "FastAPI",
    "Django",
    "Flask",
    "Tornado",
    "Graphene",
    "OpenAPI",
    "Swagger",
    "Postman",
    "OpenAPI Testing",
    "Unit Testing",
    "Integration Testing",
    "End-to-End Testing",
    "TDD",
    "BDD",
    "pytest",
    "unittest",
    "NUnit",
    "JUnit",
    "Mocha",
    "Chai",
    "Storybook",
    "UI Testing",
    "Accessibility Testing",
    "Performance Testing",
    "Load Testing",
    "JMeter",
    "k6",
    "Locust",
    "Profiling",
    "Performance Optimization",
    "Caching Strategies",
    "CD/CI Pipelines",
    "Infrastructure as Code",
    "AWS",
    "Azure",
    "GCP",
    "AWS EC2",
    "AWS S3",
    "AWS RDS",
    "AWS EKS",
    "AWS ECS",
    "AWS CloudWatch",
    "AWS IAM",
    "Azure DevOps",
    "Azure Blob Storage",
    "Azure SQL",
    "GCP Compute Engine",
    "GCP Cloud Storage",
    "GCP Cloud Run",
    "GCP IAM",
    "Cloud Networking",
    "VPC",
    "Subnets",
    "Routing",
    "NAT",
    "VPN",
    "Load Testing",
    "Data Governance",
    "Data Privacy",
    "GDPR",
    "SOC 2",
    "PCI DSS",
    "HIPAA",
    "ISO 27001",
    "Risk Management",
    "Incident Response",
    "Disaster Recovery",
    "Backup",
    "Business Continuity",
    "Technical Writing",
    "Documentation",
    "Code Review",
    "Mentoring",
    "Product Management",
    "UX Design",
    "UI Design",
    "Figma",
    "Wireframing",
    "Prototyping",
    "Design Systems",
    "SEO",
    "Analytics",
    "Google Analytics",
    "Mixpanel",
    "Amplitude",
    "Segment",
    "Feature Flags",
    "A/B Testing Tools",
    "Stripe",
    "Payments",
    "Auth0",
    "Okta",
    "SSO",
    "SAML",
    "LDAP",
    "ETCD",
    "Consul",
    "Service Discovery",
    "Rate Limiting",
    "Queueing",
    "Batch Processing",
    "Streaming",
    "Data Pipelines",
    "Edge Computing",
    "IoT",
    "Embedded Systems",
    "Robotics",
    "Computer Architecture",
    "Operating Systems",
    "Compilers",
    "Low-Level Programming",
    "Memory Management",
    "Garbage Collection",
    "API Design",
    "System Integration",
    "Scripting",
    "Automation",
    "CLI Tools",
    "Build Systems",
    "Make",
    "CMake",
    "Gradle",
    "Maven",
    "NPM",
    "Yarn",
    "PNPM",
    "Poetry",
    "Pipenv",
    "Virtualenv",
    "Conda",
    "Jupyter",
    "Notebooks",
    "Data Science",
    "Bioinformatics",
    "Geospatial",
    "GIS",
    "QGIS",
    "Computer Graphics",
    "OpenGL",
    "Vulkan",
    "WebGL",
    "AR/VR",
    "WebRTC",
    "Media Streaming",
    "Video Encoding",
    "Audio Processing",
    "Natural Language Processing",
    "Speech Recognition",
    "Text-to-Speech",
    "Recommendation Systems",
    "Search",
    "Information Retrieval",
    "Knowledge Graphs",
    "Graph Databases",
    "Anomaly Detection",
    "Fraud Detection",
    "Explainable AI",
    "Responsible AI",
    "Fairness",
    "Bias Mitigation",
    "Privacy Preserving ML",
    "Differential Privacy",
    "Homomorphic Encryption",

    # ── Healthcare & Medical ──
    "Patient Care",
    "Clinical Trials",
    "EMR/EHR",
    "Medical Coding",
    "Medical Billing",
    "Nursing",
    "Phlebotomy",
    "Pharmacy",
    "Health Informatics",
    "Telemedicine",
    "Medical Imaging",
    "Radiology",
    "Pathology",
    "Epidemiology",
    "Public Health",
    "Clinical Research",
    "Drug Safety",
    "Pharmacovigilance",
    "FDA Regulations",
    "GMP Compliance",
    "Patient Safety",
    "CPR Certification",
    "BLS Certification",
    "ACLS Certification",
    "Care Coordination",
    "Mental Health",
    "Occupational Therapy",
    "Physical Therapy",
    "Speech Therapy",
    "Nutrition",
    "Dietetics",

    # ── Finance & Accounting ──
    "Financial Modeling",
    "Financial Analysis",
    "GAAP",
    "IFRS",
    "Auditing",
    "Tax Preparation",
    "Tax Planning",
    "Bookkeeping",
    "Accounts Payable",
    "Accounts Receivable",
    "General Ledger",
    "Cost Accounting",
    "Management Accounting",
    "Budget Management",
    "Cash Flow Analysis",
    "Revenue Forecasting",
    "Risk Assessment",
    "Credit Analysis",
    "Investment Analysis",
    "Portfolio Management",
    "Bloomberg Terminal",
    "QuickBooks",
    "SAP FICO",
    "Oracle Financials",
    "Treasury Management",
    "Mergers and Acquisitions",
    "Due Diligence",
    "Valuation",
    "Financial Reporting",
    "Regulatory Compliance",
    "Anti-Money Laundering",
    "KYC",
    "Insurance Underwriting",
    "Actuarial Science",

    # ── Marketing & Sales ──
    "Content Marketing",
    "Digital Marketing",
    "Social Media Marketing",
    "Email Marketing",
    "Marketing Automation",
    "CRM",
    "Salesforce",
    "HubSpot",
    "Lead Generation",
    "Brand Strategy",
    "Brand Management",
    "Market Research",
    "Consumer Insights",
    "Competitive Analysis",
    "PPC Advertising",
    "Google Ads",
    "Facebook Ads",
    "Display Advertising",
    "Programmatic Advertising",
    "Affiliate Marketing",
    "Influencer Marketing",
    "Public Relations",
    "Media Relations",
    "Event Planning",
    "Event Management",
    "Trade Shows",
    "Sales Strategy",
    "Account Management",
    "Business Development",
    "Customer Success",
    "Customer Retention",
    "Pricing Strategy",
    "Go-to-Market Strategy",
    "Product Marketing",
    "Growth Marketing",
    "Conversion Rate Optimization",
    "Marketing Analytics",
    "Attribution Modeling",
    "Copywriting",
    "Content Strategy",
    "Demand Generation",

    # ── Human Resources ──
    "Talent Acquisition",
    "Recruitment",
    "Employee Relations",
    "HRIS",
    "Payroll Management",
    "Onboarding",
    "Performance Management",
    "Compensation and Benefits",
    "Employee Engagement",
    "Organizational Development",
    "Succession Planning",
    "Workforce Planning",
    "Training and Development",
    "Learning Management Systems",
    "Diversity and Inclusion",
    "Labor Law",
    "Employment Law",
    "Conflict Resolution",
    "Change Management",
    "HR Analytics",
    "Applicant Tracking Systems",
    "Background Checks",
    "Exit Interviews",
    "Employee Wellness",
    "Workday",
    "BambooHR",
    "ADP",

    # ── Manufacturing & Engineering ──
    "CAD",
    "AutoCAD",
    "SolidWorks",
    "CATIA",
    "Six Sigma",
    "Lean Manufacturing",
    "Quality Control",
    "Quality Assurance",
    "ISO 9001",
    "PLC Programming",
    "SCADA",
    "CNC Machining",
    "3D Printing",
    "Additive Manufacturing",
    "Supply Chain Management",
    "Inventory Management",
    "Warehouse Management",
    "Procurement",
    "Vendor Management",
    "Production Planning",
    "Process Engineering",
    "Industrial Engineering",
    "Mechanical Engineering",
    "Electrical Engineering",
    "Civil Engineering",
    "Chemical Engineering",
    "Materials Science",
    "Failure Analysis",
    "Root Cause Analysis",
    "FMEA",
    "GD&T",
    "Blueprint Reading",
    "Hydraulics",
    "Pneumatics",
    "Welding",
    "Machining",
    "Tooling",
    "Fixture Design",

    # ── Legal ──
    "Contract Law",
    "Corporate Law",
    "Intellectual Property",
    "Patent Law",
    "Trademark Law",
    "Legal Research",
    "Legal Writing",
    "Litigation",
    "Arbitration",
    "Mediation",
    "Compliance",
    "Regulatory Affairs",
    "eDiscovery",
    "Contract Negotiation",
    "Contract Management",
    "Privacy Law",
    "Data Protection Law",
    "Real Estate Law",
    "Immigration Law",
    "Environmental Law",
    "Paralegal",
    "Legal Project Management",
    "Westlaw",
    "LexisNexis",
    "Case Management",

    # ── Education & Training ──
    "Curriculum Design",
    "Curriculum Development",
    "Instructional Design",
    "EdTech",
    "Classroom Management",
    "Student Assessment",
    "Lesson Planning",
    "Special Education",
    "E-Learning",
    "Blended Learning",
    "Adult Education",
    "Academic Advising",
    "Educational Psychology",
    "Research Methodology",
    "Grant Writing",
    "Academic Writing",
    "Peer Review",
    "Moodle",
    "Canvas LMS",
    "Blackboard",
    "Google Classroom",
    "STEM Education",
    "Early Childhood Education",
    "Higher Education",
    "Tutoring",

    # ── Construction & Trades ──
    "OSHA Compliance",
    "Construction Management",
    "Project Estimation",
    "Cost Estimation",
    "Building Codes",
    "Electrical Wiring",
    "Plumbing",
    "HVAC",
    "Carpentry",
    "Masonry",
    "Roofing",
    "Concrete Work",
    "Steel Fabrication",
    "Structural Engineering",
    "Surveying",
    "Site Management",
    "Safety Management",
    "Equipment Operation",
    "Heavy Equipment",
    "Crane Operation",
    "Scaffolding",
    "Demolition",
    "Renovation",
    "Green Building",
    "LEED Certification",

    # ── Creative & Design ──
    "Adobe Creative Suite",
    "Adobe Photoshop",
    "Adobe Illustrator",
    "Adobe InDesign",
    "Adobe Premiere Pro",
    "Adobe After Effects",
    "Video Production",
    "Video Editing",
    "Motion Graphics",
    "Animation",
    "Graphic Design",
    "Typography",
    "Color Theory",
    "Photography",
    "Photo Editing",
    "Illustration",
    "Print Design",
    "Packaging Design",
    "Interior Design",
    "Architecture",
    "3D Modeling",
    "Rendering",
    "Sketch",
    "User Research",
    "Usability Testing",
    "Information Architecture",
    "Interaction Design",
    "Visual Design",
    "Brand Identity",
    "Creative Direction",
    "Art Direction",
    "Storyboarding",
    "Sound Design",
    "Audio Engineering",
    "Music Production",

    # ── Logistics & Operations ──
    "Logistics Management",
    "Fleet Management",
    "Route Optimization",
    "Freight Management",
    "Customs and Import/Export",
    "International Trade",
    "Distribution Management",
    "Last Mile Delivery",
    "Order Fulfillment",
    "Demand Planning",
    "S&OP",
    "ERP Systems",
    "SAP",
    "Oracle ERP",
    "Operations Management",
    "Facility Management",
    "Maintenance Management",
    "Asset Management",
    "Continuous Improvement",
    "Kaizen",
    "5S Methodology",
    "Value Stream Mapping",
    "Total Quality Management",

    # ── General Business & Soft Skills ──
    "Project Management",
    "PMP Certification",
    "PRINCE2",
    "Program Management",
    "Stakeholder Management",
    "Strategic Planning",
    "Business Analysis",
    "Business Intelligence",
    "Requirements Gathering",
    "Process Improvement",
    "Data-Driven Decision Making",
    "Presentation Skills",
    "Public Speaking",
    "Negotiation",
    "Critical Thinking",
    "Problem Solving",
    "Decision Making",
    "Team Leadership",
    "People Management",
    "Cross-Functional Collaboration",
    "Communication Skills",
    "Written Communication",
    "Interpersonal Skills",
    "Emotional Intelligence",
    "Time Management",
    "Conflict Management",
    "Customer Service",
    "Client Relations",
    "Vendor Relations",
    "Budget Planning",
    "Budgeting",
    "Report Writing",
    "Microsoft Office",
    "Microsoft Excel",
    "Microsoft PowerPoint",
    "Microsoft Word",
    "Google Workspace",
    "Slack",
    "Jira",
    "Asana",
    "Trello",
    "Monday.com",
    "Confluence",
    "Notion",
    "Zoom",
    "Microsoft Teams",
    "Remote Work",
    "Agile Project Management",
    "Scrum Master",
    "Product Ownership",
    "OKR",
    "KPI Management",
    "Lean Methodology",
    "Design Thinking",
    "Innovation Management",
    "Entrepreneurship",
    "Startup Experience",
]
