SKILL_LIST = [
    "HTML",
    "CSS",
    "JavaScript",
    "TypeScript",
    "Web Accessibility",
    "Responsive Design",
    "Sass",
    "Less",
    "Tailwind CSS",
    "Bootstrap",
    "Material UI",
    "Chakra UI",
    "Styled Components",
    "CSS Modules",
    "Webpack",
    "Vite",
    "Babel",
    "ESLint",
    "Prettier",
    "Jest",
    "Vitest",
    "Cypress",
    "Playwright",
    "Puppeteer",
    "React",
    "Next.js",
    "Redux",
    "Vue.js",
    "Nuxt.js",
    "Angular",
    "Svelte",
    "SvelteKit",
    "SolidJS",
    "Astro",
    "Node.js",
    "Express.js",
    "NestJS",
    "Fastify",
    "Koa",
    "Hapi",
    "Deno",
    "Bun",
    "REST APIs",
    "GraphQL",
    "Apollo",
    "gRPC",
    "WebSockets",
    "OAuth",
    "OpenID Connect",
    "JWT",
    "API Gateway",
    "Rate Limiting",
    "Caching",
    "Redis",
    "Memcached",
    "CDN",
    "Load Balancing",
    "Microservices",
    "Monolith Architecture",
    "Serverless",
    "AWS Lambda",
    "Azure Functions",
    "Google Cloud Functions",
    "Kubernetes",
    "Docker",
    "Docker Compose",
    "Helm",
    "Service Mesh",
    "Istio",
    "Linkerd",
    "Terraform",
    "Pulumi",
    "Ansible",
    "Chef",
    "Puppet",
    "CI/CD",
    "GitHub Actions",
    "GitLab CI",
    "Jenkins",
    "CircleCI",
    "Travis CI",
    "Bash",
    "Linux",
    "Unix",
    "Windows",
    "macOS",
    "Git",
    "SVN",
    "Mercurial",
    "Agile",
    "Scrum",
    "Kanban",
    "DevOps",
    "SRE",
    "Monitoring",
    "Logging",
    "Prometheus",
    "Grafana",
    "ELK Stack",
    "OpenTelemetry",
    "Datadog",
    "New Relic",
    "Splunk",
    "Python",
    "Java",
    "C",
    "C++",
    "C#",
    "Go",
    "Rust",
    "Kotlin",
    "Swift",
    "Objective-C",
    "Scala",
    "Ruby",
    "PHP",
    "Perl",
    "R",
    "MATLAB",
    "Julia",
    "Haskell",
    "Erlang",
    "Elixir",
    "Lua",
    "Dart",
    "Flutter",
    "Android",
    "iOS",
    "React Native",
    "Xamarin",
    "Unity",
    "Unreal Engine",
    "Game Development",
    "Data Structures",
    "Algorithms",
    "Big O Analysis",
    "System Design",
    "Distributed Systems",
    "Concurrency",
    "Multithreading",
    "Parallel Computing",
    "Networking",
    "TCP/IP",
    "HTTP",
    "DNS",
    "TLS",
    "SSL",
    "Network Security",
    "Cryptography",
    "Public Key Infrastructure",
    "Identity and Access Management",
    "Zero Trust",
    "Vulnerability Scanning",
    "Penetration Testing",
    "OWASP",
    "Threat Modeling",
    "Secure Coding",
    "Static Analysis",
    "Dynamic Analysis",
    "Fuzz Testing",
    "SQL",
    "PostgreSQL",
    "MySQL",
    "SQLite",
    "SQL Server",
    "Oracle",
    "MongoDB",
    "Cassandra",
    "DynamoDB",
    "Redis",
    "Neo4j",
    "CouchDB",
    "Firestore",
    "Elasticsearch",
    "Kafka",
    "RabbitMQ",
    "ActiveMQ",
    "NATS",
    "SQS",
    "SNS",
    "Event-Driven Architecture",
    "ETL",
    "ELT",
    "Data Warehousing",
    "Data Lakes",
    "Data Modeling",
    "OLTP",
    "OLAP",
    "dbt",
    "Airflow",
    "Luigi",
    "Prefect",
    "Spark",
    "Hadoop",
    "Hive",
    "Presto",
    "Trino",
    "Flink",
    "Beam",
    "Snowflake",
    "BigQuery",
    "Redshift",
    "Databricks",
    "Tableau",
    "Power BI",
    "Looker",
    "Metabase",
    "Superset",
    "Data Visualization",
    "Data Cleaning",
    "Feature Engineering",
    "Statistics",
    "Probability",
    "A/B Testing",
    "Experiment Design",
    "Time Series",
    "Forecasting",
    "Optimization",
    "Linear Algebra",
    "Calculus",
    "Machine Learning",
    "Deep Learning",
    "AI",
    "NLP",
    "Computer Vision",
    "Reinforcement Learning",
    "Supervised Learning",
    "Unsupervised Learning",
    "Semi-Supervised Learning",
    "Transfer Learning",
    "Federated Learning",
    "Model Evaluation",
    "Model Monitoring",
    "MLOps",
    "Model Serving",
    "Feature Store",
    "TensorFlow",
    "Keras",
    "PyTorch",
    "Scikit-learn",
    "XGBoost",
    "LightGBM",
    "CatBoost",
    "Hugging Face",
    "Transformers",
    "Sentence Transformers",
    "BERT",
    "RoBERTa",
    "GPT",
    "LLMs",
    "Prompt Engineering",
    "RAG",
    "Vector Databases",
    "FAISS",
    "Pinecone",
    "Weaviate",
    "Milvus",
    "Chroma",
    "LangChain",
    "LlamaIndex",
    "FastAPI",
    "Django",
    "Flask",
    "Tornado",
    "Graphene",
    "OpenAPI",
    "Swagger",
    "Postman",
    "OpenAPI Testing",
    "Unit Testing",
    "Integration Testing",
    "End-to-End Testing",
    "TDD",
    "BDD",
    "pytest",
    "unittest",
    "NUnit",
    "JUnit",
    "Mocha",
    "Chai",
    "Storybook",
    "UI Testing",
    "Accessibility Testing",
    "Performance Testing",
    "Load Testing",
    "JMeter",
    "k6",
    "Locust",
    "Profiling",
    "Performance Optimization",
    "Caching Strategies",
    "CD/CI Pipelines",
    "Infrastructure as Code",
    "AWS",
    "Azure",
    "GCP",
    "AWS EC2",
    "AWS S3",
    "AWS RDS",
    "AWS EKS",
    "AWS ECS",
    "AWS CloudWatch",
    "AWS IAM",
    "Azure DevOps",
    "Azure Blob Storage",
    "Azure SQL",
    "GCP Compute Engine",
    "GCP Cloud Storage",
    "GCP Cloud Run",
    "GCP IAM",
    "Cloud Networking",
    "VPC",
    "Subnets",
    "Routing",
    "NAT",
    "VPN",
    "Load Testing",
    "Data Governance",
    "Data Privacy",
    "GDPR",
    "SOC 2",
    "PCI DSS",
    "HIPAA",
    "ISO 27001",
    "Risk Management",
    "Incident Response",
    "Disaster Recovery",
    "Backup",
    "Business Continuity",
    "Technical Writing",
    "Documentation",
    "Code Review",
    "Mentoring",
    "Product Management",
    "UX Design",
    "UI Design",
    "Figma",
    "Wireframing",
    "Prototyping",
    "Design Systems",
    "SEO",
    "Analytics",
    "Google Analytics",
    "Mixpanel",
    "Amplitude",
    "Segment",
    "Feature Flags",
    "A/B Testing Tools",
    "Stripe",
    "Payments",
    "Auth0",
    "Okta",
    "SSO",
    "SAML",
    "LDAP",
    "ETCD",
    "Consul",
    "Service Discovery",
    "Rate Limiting",
    "Queueing",
    "Batch Processing",
    "Streaming",
    "Data Pipelines",
    "Edge Computing",
    "IoT",
    "Embedded Systems",
    "Robotics",
    "Computer Architecture",
    "Operating Systems",
    "Compilers",
    "Low-Level Programming",
    "Memory Management",
    "Garbage Collection",
    "API Design",
    "System Integration",
    "Scripting",
    "Automation",
    "CLI Tools",
    "Build Systems",
    "Make",
    "CMake",
    "Gradle",
    "Maven",
    "NPM",
    "Yarn",
    "PNPM",
    "Poetry",
    "Pipenv",
    "Virtualenv",
    "Conda",
    "Jupyter",
    "Notebooks",
    "Data Science",
    "Bioinformatics",
    "Geospatial",
    "GIS",
    "QGIS",
    "Computer Graphics",
    "OpenGL",
    "Vulkan",
    "WebGL",
    "AR/VR",
    "WebRTC",
    "Media Streaming",
    "Video Encoding",
    "Audio Processing",
    "Natural Language Processing",
    "Speech Recognition",
    "Text-to-Speech",
    "Recommendation Systems",
    "Search",
    "Information Retrieval",
    "Knowledge Graphs",
    "Graph Databases",
    "Anomaly Detection",
    "Fraud Detection",
    "Explainable AI",
    "Responsible AI",
    "Fairness",
    "Bias Mitigation",
    "Privacy Preserving ML",
    "Differential Privacy",
    "Homomorphic Encryption",
]
